<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_score</name>
   <tag></tag>
   <elementGuidId>f6711fe5-69be-4e44-af00-4b001a934464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17068619-d642-4d2d-b139-df062d948c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>76eecc52-65af-43e7-98c9-a8f9c7e4aafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score</value>
      <webElementGuid>ee2296d4-c72e-4016-a663-0686d1836135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score</value>
      <webElementGuid>58621e54-81f3-4816-a378-71ee1c355626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Score...</value>
      <webElementGuid>1c38b59c-8545-4dcc-a5f6-a8dd0791c4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02f9e128-1bdf-4789-baac-e9522bb8f936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score&quot;)</value>
      <webElementGuid>245b0eb7-c776-468f-8a51-cb5c40538941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score']</value>
      <webElementGuid>eaf9f89a-3f45-4f07-8bb6-19df868f9548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5c217c7b-e8f4-4641-974a-828b21f901ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'score' and @name = 'score' and @placeholder = 'Score...' and @type = 'text']</value>
      <webElementGuid>3fc937cb-fb89-4d72-b3d0-330cc6092f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
